### ISSUE TITLE
Membrane Protein Equilibration Protocal

### ISSUE THREAD

**Issue by allisonbarkdull** [forlilab/cosolvkit#18]
It would be useful if there was support for minimization/equilibration of membrane-protein systems. I would recommend implementing this protocol for proper equilibration:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/allis/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/allis/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/allis/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Step | Ensemble | Time (ps) | Backbone Heavy   Atoms Restraint | Sidechain Heavy   Atoms   Restraint | Lipid Position   Restraint | Lipid Dihedral   Restraint | Ion Restraint
-- | -- | -- | -- | -- | -- | -- | --
Minimization | NVT | 20 | 10 | 5.0 | 5 | 500 | 10
1 | NPT/NPAT| 250 | 10 | 5.0 | 5 | 500 | 0
2 | NPT/NPAT | 250 | 5.0 | 2.5 | 5 | 200 | 0
3 | NPT/NPAT| 500 | 2.5 | 1.25 | 2 | 100 | 0
4 | NPT/NPAT| 500 | 1.0 | 0.5 | 1 | 100 | 0
5 | NPT/NPAT| 500 | 0.5 | 0.25 | 0.2 | 50 | 0
6 | NPT/NPAT| 500 | 0.1 | 0.05 | 0 | 0 | 0

<b><span style='font-size:8.0pt;line-height:107%;font-family:"Garamond",serif;
mso-fareast-font-family:Calibri;mso-fareast-theme-font:minor-latin;mso-bidi-font-family:
Arial;color:black;mso-ansi-language:EN-US;mso-fareast-language:EN-US;
mso-bidi-language:AR-SA'></span></b><span style='font-size:8.0pt;
line-height:107%;font-family:"Garamond",serif;mso-fareast-font-family:Calibri;
mso-fareast-theme-font:minor-latin;mso-bidi-font-family:Arial;color:black;
mso-ansi-language:EN-US;mso-fareast-language:EN-US;mso-bidi-language:AR-SA'>.
All units for restraint constants are in kcal×mol<sup>-1</sup>×Å<sup>-2</sup></span>
</body>

</html>

**Comment by nbruciaferri** [comment]
@mallanos  what's the status on this?

**Comment by mallanos** [comment]
We've decided that this does not belong to CosolvKit. If the user needs a special equilibration protocol it could just use the input files generated and run it elsewhere with custom scripts
