### ISSUE TITLE
Problem installing cosolvkit through Conda

### ISSUE THREAD

**Issue by Alessandra1398** [forlilab/cosolvkit#34]
Following the instructions in the READ ME file for the Conda procedure, when I have to create the environment I get the following error:

Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - environment.yml

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I have already downloaded the software .zip file from here and unzipped it in a folder, activated Conda with python vers >3.10 and proceeded following the installation instructions, can you help me solving this issue? thanks.

**Comment by nbruciaferri** [comment]
Hi, thanks for using installing CosolvKit! It's not completely clear to me what kind of installation did you follow.
In the README I suggest to just create a new conda environment with `python>3.10`, activate the new environment and then do `conda install cosolvkit`. Then you can use cosolvkit features easily.

Please let me know if you have other problems!

Thanks!

**Comment by Alessandra1398** [comment]
Hi, thanks for the quick reply, I followed this part of the READ.ME, but as I wrote in the issue I got the error that I reported.
conda install --channel conda-forge::cosolvkit
conda create -n cosolvkit -c conda-forge -f environment.yml
conda activate cosolvkit
pip instal cosolvkit

Following your advice and creating a new conda environment with python>3.10 and then doing conda install cosolvkit, It was able to download all the depencies.
Thanks for the help
