### ISSUE TITLE
ImportError: cannot import name 'qmc' from 'scipy.stats'

### ISSUE THREAD

**Issue by Alessandra1398** [forlilab/cosolvkit#36]
Hi! After following the instructions you've given me in the former issue raised "Problem installing cosolvkit through Conda #34", I tried to follow the "Quick tutorial" part in the READ ME, but after executing the command create_cosolvent_system -c config.json, I get an error importing 'qmc' from 'scipy.stats'.
I tried two possible solutions: installing in the environment scipy 1.7 with conda install scipy=1.7, and installing scipy with sudo apt-get install python3-scipy,  but It didn't work and I still get this error.
Are you familiar with this problem or could you suggest me a possible solution? Thanks in advance for the help.

**Comment by nbruciaferri** [comment]
Hi Alessandra, sorry for the late reply. It is a little hard to say what's wrong with your environment without giving a look at it. Conda should take care of the right versions and all the tests that were done in lab and in conda-forge pre-release passed without any problem.

Could you please provide what OS are you using as well as a list of the packages in your environment (`conda list`) after activating the environment created for cosolvkit?

Also, did you install it from scratch as a new and clean environment? Did you install other packages besides the ones that were listed in the README? It is possible that if you installed other packages that need specific versions of `scipy` then the version has changed to satisfy those requirements.

Thanks,

Niccolo.

**Comment by nbruciaferri** [comment]
It looks like if calling `create_cosolvent_system` with `sudo` will cause the interpreter to use the conda packages in the `base` environment instead of the one created for `cosolvkit`.

The issue was resolved.
